database:
  connection_string: "<inser your connection string according to postgresql documentation https://www.postgresql.org/docs/9.5/libpq-connect.html#LIBPQ-CONNSTRING>"

server:
  port: 8080
  limit: 20 #default sql limit for all paginated endpoints

logger:
  verbosity: debug