name:                metalampserver
version:             0.1.0.0
github:              "sl1depengwyn/metalampserver"
license:             BSD3
author:              "Maxim Filonov"
maintainer:          "max.pengwyn@gmail.com"
copyright:           "2022 Maxim Filonov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/metalampserver#readme>

dependencies:
- base >= 4.7 && < 5
- universum
- bytestring
- text
- mtl
- beam-core
- beam-postgres
- beam-migrate
- microlens
- aeson
- aeson-extra
- yaml
- time
- cryptonite
- base64
- postgresql-simple
- resource-pool
- fast-logger
- servant
- servant-server
- servant-auth
- servant-auth-server
- wai
- warp

default-extensions: 
- NoImplicitPrelude

library:
  source-dirs: src

executables:
  metalampserver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metalampserver

tests:
  metalampserver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metalampserver
